### ISSUE TITLE
关于netty 编码和解码器

### ISSUE THREAD

**Issue by weiki08** [zhu410289616/RHSocketKit#1]
你好，关注您的代码很久了，我在开发中遇到一个问题，服务器端用的是netty4 提供的编码器和解码器，服务器部分代码如下
            public void initChannel(SocketChannel ch) throws Exception {  
                ChannelPipeline pipeline = ch.pipeline();  

```
           pipeline.addLast(new ProtobufVarint32FrameDecoder());
            pipeline.addLast(new ProtobufDecoder(PushMgsPaket.IMMessage.getDefaultInstance()));
            pipeline.addLast(new ProtobufVarint32LengthFieldPrepender());
            pipeline.addLast(new ProtobufEncoder());

            pipeline.addLast(new TcpServerHandler());  
        }  
```

那么对应的IOS端有没有对应的编码和解码与之匹配的

**Comment by zhu410289616** [comment]
![2012102121555711](https://cloud.githubusercontent.com/assets/4067900/15473628/898e7acc-2133-11e6-9147-0bfab60ae8c3.jpg)
（1）Protobuf序列化的数据不包括消息类型，接受方没办法初始化对应的类型进行反序列化操作。（2）虽然netty中有了消息长度的编解码，但是这个长度是不定长的，所以接受方不能正常得到protobuf的数据内容。因为上面的原因，我也没想好怎么实现配合netty中protobuf的编解码。我的方式是和其他编解码结合使用。上面的截图是个不错的方案，不过为了安全起见，你最好在协议头中做一些扩展。 @WeikiForNtt

**Comment by weiki08** [comment]
谢谢你提供的思路，另外请教下你所说的和其他编解码结合使用，具体是怎么使用的？和哪一个编解码结合使用的？

**Comment by zhu410289616** [comment]
就按照上面图片中的协议结构 前面的几个数据字段是协议头 后面的protobufdata是数据内容 通过自定义的编码解码器得到protobufdata的数据内容 然后把这个protobufdata和data对应的结构类型丢给后面的protobuf编码解码器去处理解包 也就是包含了两个编码解码器 一个是自定义的编码解码器 另一个是protobuf的编码解码器

**Comment by weiki08** [comment]
特别感谢@zhu410289616

**Comment by weiki08** [comment]
你好！

参照了Netty的源码之后，我这边封装了一套编码解码器，可以完美支持netty自带的哪个编码解码器，我整理一下共有给你，还请指教！

在 2016-05-24 21:31:27，"朱如洪" notifications@github.com 写道：

就按照上面图片中的协议结构 前面的几个数据字段是协议头 后面的protobufdata是数据内容 通过自定义的编码解码器得到protobufdata的数据内容 然后把这个protobufdata和data对应的结构类型丢给后面的protobuf编码解码器去处理解包 也就是包含了两个编码解码器 一个是自定义的编码解码器 另一个是protobuf的编码解码器

**Comment by zhu410289616** [comment]
@WeikiForNtt 厉害 
qq：410289616  谢谢分享～哈哈

**Comment by zhu410289616** [comment]
@WeikiForNtt 现在增加了正对netty的protobuf编解码了。
之前的多个编解码组合方式保留，增加了可以互通的嵌套方式。
使用方式在RHSocketKitDemo中。

**Comment by wubuer** [comment]
同问一下，对于netty默认实现的ObjectEncoder（）及ObjectDecider（），RHSocketKit中有对应的那一套编解码呢？还是同样需要自定义呢？刚接触这块，不懂请教
