### ISSUE TITLE
错误

### ISSUE THREAD

**Issue by ZhongXianGuan** [zhu410289616/RHSocketKit#2]
- (uint32_t)uint32FromBytes:(NSData *)data
  {
  NSAssert(data.length == 4, @"uint16FromBytes: (data length != 4)");
  
  uint32_t val0 = 0;
  uint32_t val1 = 0;
  uint32_t val2 = 0;
  uint32_t val3 = 0;
  [data getBytes:&val0 range:NSMakeRange(0, 1)];
  [data getBytes:&val1 range:NSMakeRange(1, 1)];
  [data getBytes:&val2 range:NSMakeRange(2, 1)];
  [data getBytes:&val3 range:NSMakeRange(3, 1)];
  
  uint32_t dstVal = (val0 & 0xff) + ((val1 << 8) & 0xff00) + ((val1 << 16) & 0xff0000) + ((val1 << 24) & 0xff000000);
  return dstVal;
  }

dstval 算错了

**Comment by zhu410289616** [comment]
@ZhongXianGuan 没问题吧？😄

**Comment by Tony-Kwan** [comment]
uint32_t dstVal = (val0 & 0xff) + ((val1 << 8) & 0xff00) + ((val1 << 16) & 0xff0000) + ((val1 << 24) & 0xff000000);
-->
uint32_t dstVal = (val0 & 0xff) + ((val1 << 8) & 0xff00) + ((val2 << 16) & 0xff0000) + ((val3 << 24) & 0xff000000);
应该是这样吧

**Comment by zhu410289616** [comment]
@Tony-Kwan 见笑了 一下子没反应过来 后面已经把这些方法替换掉了 谢谢回复～哈哈
